services:
  # Databases
  nosql-db:
    image: mongo
    profiles: ["prod", "dev"]
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    profiles: ["prod"]
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/products/node_modules
    env_file:
      - ./products/.env.dev

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    profiles: ["prod"]
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/shopping/node_modules
    env_file:
      - ./shopping/.env.dev

  customer:
    build:
      dockerfile: Dockerfile.prod
      context: ./customer
    profiles: ["prod"]
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app/
    env_file:
      - ./customer/.env.prod

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    profiles: ["prod"]
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - 80:80
