# Ignore everything
*

# Allowed files and directories
!/build
!/dist
!/src
!/public
!/package*.json

# Ignore unnecessary files inside allowed directories
# This should go after the allowed directories
