# Ignore everything
*

# Allowed files and directories
!/src
!/.eslint*
!/.prettierrc
!/tsconfig.json
!/package*.json

# Ignore unnecessary files inside allowed directories
# This should go after the allowed directories
**/*~
**/*.log
**/.DS_Store
**/Thumbs.db
